server:
  port: 8082

spring:
  application:
    name: post-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

  datasource:
    url: jdbc:postgresql://localhost:5432/post_service_db
    username: postuser
    password: postpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # dev only
    properties:
      hibernate:
        default_schema: post_service
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
